import type { Metadata } from "next";
import { PostArticle } from "@/components/post-article";
import { getPost } from "@/lib/posts";

const MEDIUM_URL =
  "https://medium.com/@richard_84017/i-connected-dark-energy-dark-matter-and-anti-matter-matter-through-blackhole-inversions-as-ae974004d499";

const post = getPost("dark-energy-dark-matter-blackhole-inversions")!;

export const metadata: Metadata = {
  title: post.title,
  description: post.dek,
  alternates: {
    canonical:
      "https://richardthebruce.com/writing/dark-energy-dark-matter-blackhole-inversions",
  },
  openGraph: {
    title: post.title,
    description: post.dek,
    type: "article",
    publishedTime: post.date,
    authors: ["Richard Wayne"],
  },
};

export default function DarkEnergyBlackholeInversionsPage() {
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    headline: post.title,
    author: {
      "@type": "Person",
      name: "Richard Wayne",
      url: "https://richardthebruce.com",
    },
    datePublished: post.date,
    description: post.dek,
    url: "https://richardthebruce.com/writing/dark-energy-dark-matter-blackhole-inversions",
    sameAs: MEDIUM_URL,
    inLanguage: "en",
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <PostArticle post={post}>
        <p>
          <a
            href={MEDIUM_URL}
            target="_blank"
            rel="noreferrer noopener"
            className="text-sm text-[var(--accent)] underline underline-offset-4"
          >
            Read the original on Medium &rarr;
          </a>
        </p>

        <p>
          Reality begins with a single Matter/Anti-Matter particle, particle
          one, particle two. These two particles spontaneously appear and
          explode into a big bang. Reality in the framework of being or not
          being does not consistently make sense without both components.
          Reality must always be in approach to collapse or becoming.
        </p>
        <p>
          After this revelation, I was able to deduce a framework for Dark
          Energy by conceptualizing Blackholes as inversions where matter and
          anti matter converge and flip from probability into absolute, or
          state.
        </p>
        <p>
          Blackholes are possibility windows that convert anti-matter, which
          is also Dark Matter (latent potential energy) into Matter. Using
          the emerging factor of particle physics and the electromagnetic
          spectrum matter when conscious or subconscious creates a decay
          field where the decay field is a summoning of one potential or
          another from possible to actual. Essentially, decay is just an
          indication of what you are becoming or are likely to become.
        </p>
        <p>
          I solved Particle Physics conceptualizing decay as an angular
          momentum of becoming towards one possibility or another where decay
          represents the thing you are becoming and the collapse of
          potentials into a single vector of occurrence, essentially
          decreasing amplitude of potentials across a multi-dimensional
          framework into a single point where the point is what happened and
          the decay is also a collapse of potential possibilities with a
          trail of sub atomic particle excitation indicating its own
          becoming.
        </p>
        <p>
          To summarize, we may use emerging factors of electromagnetic fields
          generated by subatomic particles, humans or planets to discover
          their decaying angularity towards a least likely or most likely
          window of becoming where decay indicates the inversely related dark
          energy potential you are spinning into existing.
        </p>
        <p>
          Decay is a relative and proportional relationship of Dark Energy
          and Energy Dark Matter and Matter. Decay collapses Dark Energy,
          latent potential energy into non-latent non-uniform matter
          (occurrence). Decay is a vector verse/inverse of size for
          matter/anti-matter relationships.
        </p>
        <p>
          Potentials decay into outcome and decay, then collapses and begins
          again, and you may think about decay as tensor vectors of objects
          from nothing moving towards their own potential. Electromagnetic
          fields are indicative of matter summoning dark matter into reality
          where at a blackhole flips anti-matter into Matter. What you think
          is what you become.
        </p>
        <p>
          Dark Matter and Matter are things becoming and unbecoming that are
          less likely or more likely until one version or another is absolute
          or has occurred. Dark Matter = potential matter = state.
        </p>
        <p>
          With this framework, all Math, all physics is unified and solvable
          from a single field of approach.
        </p>
      </PostArticle>
    </>
  );
}
